### ISSUE TITLE
Semantic Domains not showing in Browse view

### ISSUE THREAD

**Issue by peteroatley** [sillsdev/webonary#813]
@phillip-hopper It looks like something has changed in FLEx that causes semantic domains to not be processed correctly. Older dictionaries are fine but recent uploads don't show Semantic domains in the browse view.

<img width="50%" height="50%" alt="Image" src="https://github.com/user-attachments/assets/3293418d-1e9d-49ed-b122-3e46713b4645" />

<img width="50%" height="50%" alt="Image" src="https://github.com/user-attachments/assets/4d7e3fbc-d581-4643-9f32-e2f2aa728844" />

https://www.webonary.org/test-oatley5/browse/categories/?semdomain=Weather&semnumber=1.1.3.

Back in March we found a change in the HTML data being uploaded for RTL scripts (Issue #795) . Perhaps they've made another change.

**Comment by phillip-hopper** [comment]
@peteroatley, the semantic domains for this particular dictionary aren't displaying because the name of the field is `abbreviation-6` instead of the expected `abbreviation`. I have no idea why. It's just a coincidence that the domain number in the example below ends with 6. I looked at others, and they are all `abbreviation-6` regardless of what the domain number is.

This is an example,

```
<span class="semanticdomain">
  <span class="abbreviation-6">
    <span lang="en">1.6</span>
  </span>
  <span class="name">
    <span lang="en">Animal</span>
  </span>
</span>
```

**Comment by peteroatley** [comment]
@phillip-hopper Thanks, I'll write-up a JIRA issue for FLEx

**Comment by peteroatley** [comment]
https://jira.sil.org/browse/LT-22246

**Comment by phillip-hopper** [comment]
@peteroatley, I received this message from Jason. Apparently that change was intentional and has a purpose. I will try to work around it.
> There is an issue with the import of Webonary caused by semi-recent changes to FieldWorks. Some of the css classes which we generate will have a -n (where n is a number which indicates the number of unique styles with that name generated to this point)

**Comment by peteroatley** [comment]
I thought it was working but when I re-uploaded my test database the Semantic Domain Page said "No entries exist for...". 
https://www.webonary.work/test-oatley5/browse/categories/?semdomain=Weather&semnumber=1.1.3.

I have a test site which already had the new tags and when I first looked at Semantic domains they were displayed but after re-uploading they are no longer displayed.

There seems to be a problem with the formatting of entries for some dictionaries on .work. The entries are correctly formatted on .org.

Here is an example from Lugwere:

This is .org
https://www.webonary.org/lugwere/gd769c739-a96e-42f9-a79c-52e85f58f5b0/

<img width=50% height=50% alt="Image" src="https://github.com/user-attachments/assets/8c1aca65-cc76-4b77-9e9a-b8cf2016484c" />

This is .work:
https://www.webonary.work/lugwere/gd769c739-a96e-42f9-a79c-52e85f58f5b0/

<img width=50% height=50% alt="Image" src="https://github.com/user-attachments/assets/299d571c-ddf8-4776-8b78-c243883be140" />

Halbi is similar: https://www.webonary.work/halbi/gef558c7d-4d0e-4ee8-810b-68c194537c55/

**Comment by phillip-hopper** [comment]
@peteroatley, the different styling is expected, and shouldn't be a problem. The dictionaries copied from .org to .work will be missing some of these files. Re-uploading them to .work should fix the styling.

**Comment by phillip-hopper** [comment]
@peteroatley, it looks like the problem was due to caching. The class name for semantic domain abbreviations changed from `abbreviation-6` to `abbreviation-4`. I set it so this should be cleared when new data is uploaded to the cloud.

**Comment by peteroatley** [comment]
@phillip-hopper - Hi Phil, It looks like the Semantic Domain problem isn't quite solved. Entries with a '-n' at the end of the 'semanticdomains' tag don't appear in the semantic domain list. I'm not certain if this is the problem but I found a couple of entries like this which are missing from the list.

This page shows two entries the first 'ᦶᦈᧃ cæn¹' doesn't appear in the list for Moon and the second 'ᦶᦈᧃ ᦑ ᦃᧆ cæn¹taxat²' does.

https://www.webonary.org/test-oatley4?s=%E1%A6%B6%E1%A6%88%E1%A7%83&search=Search&key=khb&semantic_domain=&search_options_set=1&match_whole_words=1&lang=en

Link to Moon Semantic Domain:
https://www.webonary.org/test-oatley4/browse/categories/?semdomain=Moon&semnumber=1.1.1.1.&lang=en

'ᦶᦈᧃ cæn¹'
<img width="40%" height="40%" alt="Image" src="https://github.com/user-attachments/assets/9030989c-e880-4df8-8e9c-27481278eb4c" />

 'ᦶᦈᧃ ᦑ ᦃᧆ cæn¹taxat²'
<img width="40%" height="40%" alt="Image" src="https://github.com/user-attachments/assets/b4877572-f256-48d9-af79-65f917f1fff1" />

**Comment by phillip-hopper** [comment]
@peteroatley, it looks like the latest Flex upload has totally broken Webonary semantic domains. I'm going to undo the changes I made and take a different approach.

**Comment by phillip-hopper** [comment]
@peteroatley, that last test actually created 2 separate fields in the database. There's no easy fix for that one. The upload from Flex is now officially broken. 

<img width="1162" height="559" alt="Image" src="https://github.com/user-attachments/assets/4a00b770-bdc8-429c-b91d-5b04ee6b6445" />

**Comment by peteroatley** [comment]
@phillip-hopper I tested uploading the Lue database again and it still has the same problem that only the minor entries display.

https://www.webonary.work/test-oatley

Main Entry - Moon - ᦵᦡᦲᧃ
https://www.webonary.org/test-oatley4/browse/browse-vernacular/?key=khb&letter=%E1%A6%A1&lang=en

Minor Entry (Compound Word) - Lunar Eclipse - ᦷᦂᧇ ᦂᦲᧃ ᦵᦡᦲᧃ
https://www.webonary.org/test-oatley4/browse/browse-vernacular/?key=khb&letter=%E1%A6%82&lang=en

**Comment by peteroatley** [comment]
@phillip-hopper The semantic domains page gives a critcal error when trying to display a category with entries.

<img width="40%" height="40%" alt="Image" src="https://github.com/user-attachments/assets/2c864273-f612-4ff4-a5f4-90d8aa3c4c28" />

website: https://www.webonary.work/test-oatley/

Sem Dom page: https://www.webonary.work/test-oatley/browse/categories/?semdomain=Universe,%20creation&semnumber=1.
